// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(serena))]
    partial class serenaModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.models.cita", b =>
                {
                    b.Property<int>("id_cita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cita");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_cita"));

                    b.Property<string>("estado_cita")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("estado_cita");

                    b.Property<DateTime>("fecha_hora")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_hora");

                    b.Property<int>("id_usuario_aprendiz")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_aprendiz");

                    b.Property<int?>("id_usuario_aprendiz_navegacionid_usuario")
                        .HasColumnType("int");

                    b.Property<int>("id_usuario_psicologo")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_psicologo");

                    b.Property<int?>("id_usuario_psicologo_navegacionid_usuario")
                        .HasColumnType("int");

                    b.Property<string>("motivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("motivo");

                    b.HasKey("id_cita");

                    b.HasIndex("id_usuario_aprendiz");

                    b.HasIndex("id_usuario_aprendiz_navegacionid_usuario");

                    b.HasIndex("id_usuario_psicologo");

                    b.HasIndex("id_usuario_psicologo_navegacionid_usuario");

                    b.ToTable("cita", (string)null);
                });

            modelBuilder.Entity("WebApplication1.models.diario", b =>
                {
                    b.Property<int>("id_diario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_diario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_diario"));

                    b.Property<bool>("compartir_sp")
                        .HasColumnType("bit")
                        .HasColumnName("compartir");

                    b.Property<string>("contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contenido");

                    b.Property<DateTime>("fecha_apertura")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_diario");

                    b.Property<int>("id_usuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("id_diario");

                    b.HasIndex("id_usuario");

                    b.ToTable("diario", (string)null);
                });

            modelBuilder.Entity("WebApplication1.models.emergencia", b =>
                {
                    b.Property<int>("id_emergencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_emergencia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_emergencia"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("fecha_emergencia")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_emergencia");

                    b.Property<int>("id_usuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("id_emergencia");

                    b.ToTable("emergencia", (string)null);
                });

            modelBuilder.Entity("WebApplication1.models.estado_de_animo", b =>
                {
                    b.Property<int>("id_estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_estado"));

                    b.Property<DateTime>("fecha_estado")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_estado");

                    b.Property<int>("id_usuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("nombre_estado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_estado");

                    b.HasKey("id_estado");

                    b.HasIndex("id_usuario");

                    b.ToTable("estado_de_animo", (string)null);
                });

            modelBuilder.Entity("WebApplication1.models.formulario", b =>
                {
                    b.Property<int>("id_formulario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_formulario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_formulario"));

                    b.Property<int>("id_usuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("nombre_formulario")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre_formulario");

                    b.Property<int?>("usuarioid_usuario")
                        .HasColumnType("int");

                    b.HasKey("id_formulario");

                    b.HasIndex("usuarioid_usuario");

                    b.ToTable("formulario", (string)null);
                });

            modelBuilder.Entity("WebApplication1.models.historial_cita", b =>
                {
                    b.Property<int>("id_h_cita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_h_cita");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_h_cita"));

                    b.Property<DateTime>("fecha_cambio")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_cambio");

                    b.Property<int>("id_cita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cita");

                    b.Property<string>("observaciones_historial")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observacion_historial");

                    b.HasKey("id_h_cita");

                    b.HasIndex("id_cita");

                    b.ToTable("historial_cita", (string)null);
                });

            modelBuilder.Entity("WebApplication1.models.historial_clinico", b =>
                {
                    b.Property<int>("id_h_clinico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_h_clinico");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_h_clinico"));

                    b.Property<string>("antecedentes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("antecedentes");

                    b.Property<string>("condiciones")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("condiciones");

                    b.Property<DateTime>("fecha_apertura")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_apertura");

                    b.Property<int>("id_usuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("num_ficha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("num_ficha");

                    b.HasKey("id_h_clinico");

                    b.HasIndex("id_usuario")
                        .IsUnique();

                    b.ToTable("historial_clinico", (string)null);
                });

            modelBuilder.Entity("WebApplication1.models.menu", b =>
                {
                    b.Property<int>("id_menu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_menu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_menu"));

                    b.Property<string>("nombre_menu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_menu");

                    b.HasKey("id_menu");

                    b.ToTable("menu", (string)null);
                });

            modelBuilder.Entity("WebApplication1.models.menu_rol", b =>
                {
                    b.Property<int>("id_menu_rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_menu_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_menu_rol"));

                    b.Property<int>("id_menu")
                        .HasColumnType("int")
                        .HasColumnName("id_menu");

                    b.Property<int>("id_rol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.HasKey("id_menu_rol");

                    b.HasIndex("id_menu");

                    b.HasIndex("id_rol");

                    b.ToTable("menu_rol", (string)null);
                });

            modelBuilder.Entity("WebApplication1.models.publicaciones", b =>
                {
                    b.Property<int>("id_publicaciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_publicacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_publicaciones"));

                    b.Property<string>("contenido")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contenido");

                    b.Property<DateTime>("fecha_publicacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_publicacion");

                    b.Property<int>("id_usuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("titulo");

                    b.HasKey("id_publicaciones");

                    b.ToTable("publicaciones", (string)null);
                });

            modelBuilder.Entity("WebApplication1.models.rol", b =>
                {
                    b.Property<int>("id_rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_rol"));

                    b.Property<string>("nombre_rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_rol");

                    b.HasKey("id_rol");

                    b.ToTable("rol", (string)null);
                });

            modelBuilder.Entity("WebApplication1.models.usuario", b =>
                {
                    b.Property<int>("id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_usuario"));

                    b.Property<string>("contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("contrasena");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<int>("id_rol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<string>("nombre_usuario")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_usuario");

                    b.HasKey("id_usuario");

                    b.HasIndex("id_rol");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("WebApplication1.models.cita", b =>
                {
                    b.HasOne("WebApplication1.models.usuario", null)
                        .WithMany()
                        .HasForeignKey("id_usuario_aprendiz")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WebApplication1.models.usuario", "id_usuario_aprendiz_navegacion")
                        .WithMany()
                        .HasForeignKey("id_usuario_aprendiz_navegacionid_usuario");

                    b.HasOne("WebApplication1.models.usuario", null)
                        .WithMany()
                        .HasForeignKey("id_usuario_psicologo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WebApplication1.models.usuario", "id_usuario_psicologo_navegacion")
                        .WithMany()
                        .HasForeignKey("id_usuario_psicologo_navegacionid_usuario");

                    b.Navigation("id_usuario_aprendiz_navegacion");

                    b.Navigation("id_usuario_psicologo_navegacion");
                });

            modelBuilder.Entity("WebApplication1.models.diario", b =>
                {
                    b.HasOne("WebApplication1.models.usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("WebApplication1.models.estado_de_animo", b =>
                {
                    b.HasOne("WebApplication1.models.usuario", "usuario")
                        .WithMany("estado_de_animo")
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("WebApplication1.models.formulario", b =>
                {
                    b.HasOne("WebApplication1.models.usuario", null)
                        .WithMany("formularios")
                        .HasForeignKey("usuarioid_usuario");
                });

            modelBuilder.Entity("WebApplication1.models.historial_cita", b =>
                {
                    b.HasOne("WebApplication1.models.cita", "cita")
                        .WithMany("historial_citas")
                        .HasForeignKey("id_cita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cita");
                });

            modelBuilder.Entity("WebApplication1.models.historial_clinico", b =>
                {
                    b.HasOne("WebApplication1.models.usuario", "usuario")
                        .WithOne("historial_Clinico")
                        .HasForeignKey("WebApplication1.models.historial_clinico", "id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("WebApplication1.models.menu_rol", b =>
                {
                    b.HasOne("WebApplication1.models.menu", "menu")
                        .WithMany("menu_rol")
                        .HasForeignKey("id_menu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.models.rol", "rol")
                        .WithMany("menu_rol")
                        .HasForeignKey("id_rol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("menu");

                    b.Navigation("rol");
                });

            modelBuilder.Entity("WebApplication1.models.usuario", b =>
                {
                    b.HasOne("WebApplication1.models.rol", "rol")
                        .WithMany("usuario")
                        .HasForeignKey("id_rol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("rol");
                });

            modelBuilder.Entity("WebApplication1.models.cita", b =>
                {
                    b.Navigation("historial_citas");
                });

            modelBuilder.Entity("WebApplication1.models.menu", b =>
                {
                    b.Navigation("menu_rol");
                });

            modelBuilder.Entity("WebApplication1.models.rol", b =>
                {
                    b.Navigation("menu_rol");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("WebApplication1.models.usuario", b =>
                {
                    b.Navigation("estado_de_animo");

                    b.Navigation("formularios");

                    b.Navigation("historial_Clinico");
                });
#pragma warning restore 612, 618
        }
    }
}
